# Generated by Django 4.1.6 on 2023-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_msg',
            name='msg',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
