# Generated by Django 4.1.6 on 2023-02-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_alter_clients_msg_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients_msg',
            old_name='email',
            new_name='email_contact_us',
        ),
        migrations.RenameField(
            model_name='clients_msg',
            old_name='msg',
            new_name='message_contact_us',
        ),
        migrations.RenameField(
            model_name='clients_msg',
            old_name='name',
            new_name='name_contact_us',
        ),
    ]
