# Generated by Django 4.1.6 on 2023-02-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0004_alter_clients_msg_email_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField(max_length=100)),
                ('news_title', models.CharField(max_length=50)),
                ('news_image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('news_activate', models.BooleanField(default=False)),
            ],
        ),
    ]
