# Generated by Django 4.1.6 on 2023-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(max_length=10000),
        ),
    ]
