# Generated by Django 4.1.6 on 2023-02-17 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0006_alter_news_news_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_team_host_name', models.CharField(choices=[('Real Madrid', 'Real Madrid'), ('FC Barcelona', 'FC Barcelona'), ('Elche CF', 'Elche CF'), ('CA Osasuna', 'CA Osasuna'), ('Atlético de Madrid', 'Atlético de Madrid')], max_length=50)),
                ('game_team_opponent_name', models.CharField(choices=[('Real Madrid', 'Real Madrid'), ('FC Barcelona', 'FC Barcelona'), ('Elche CF', 'Elche CF'), ('CA Osasuna', 'CA Osasuna'), ('Atlético de Madrid', 'Atlético de Madrid')], max_length=50)),
                ('game_time', models.DateTimeField(default=datetime.datetime.now)),
                ('game_stadium', models.CharField(choices=[('Camp Nou', 'Camp Nou'), ('Martinez Valero', 'Martinez Valero'), ('El Sadar', 'El Sadar'), ('Metropolitano', 'Metropolitano'), ('Santiago Bernabeu', 'Santiago Bernabeu')], max_length=50)),
                ('game_team_opponent_logo', models.ImageField(upload_to='opponents_photos')),
                ('game_team_host_logo', models.ImageField(upload_to='hosts_photos')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='news_photos/%y/%m/%d'),
        ),
    ]
