# Generated by Django 4.1.6 on 2023-02-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0007_matches_alter_news_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
