# Generated by Django 4.1.6 on 2023-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0008_delete_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.TextField(max_length=200)),
                ('user_password', models.TextField(max_length=200)),
            ],
        ),
    ]
