# Generated by Django 4.1.6 on 2023-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0010_alter_login_user_mail_alter_login_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_auth_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='user_first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='user_last_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
