# Generated by Django 4.1.6 on 2023-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0011_login_user_auth_true_login_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_mail',
            field=models.CharField(max_length=200),
        ),
    ]
